[tool.poetry]
name = "aletheia"
version = "0.1.0"
description = "Context-aware browser extension backend using LangGraph on AWS Lambda."
authors = ["Marty McEnroe"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.34"
langchain = "^1.0.8"
langchain-aws = "^1.0.0"
langgraph = "^1.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.1,<10.0.0)"
]
