#!/bin/bash
# gemini-model-check.sh - Detect Gemini model downgrades with retry support
# Generated by AgentOS for Aletheia
#
# Usage: ./tools/gemini-model-check.sh "prompt text" [required-model]
#
# This script invokes Gemini CLI with JSON output and validates that the
# correct model tier is used. If Gemini downgrades to a lower model due to
# quota exhaustion, the script aborts and reports the issue.
#
# NEW: Uses AgentOS gemini-retry.py for automatic retry on capacity errors.
#
# Exit codes:
#   0 - Success (correct model used)
#   1 - Gemini CLI failed to execute
#   2 - Quota exhausted (daily limit, non-retryable)
#   3 - Model downgrade detected

set -euo pipefail

# Parse arguments
PROMPT="$1"
REQUIRED_MODEL="${2:-gemini-3-pro-preview}"

# AgentOS retry tool location
RETRY_TOOL="/c/Users/mcwiz/Projects/AgentOS/tools/gemini-retry.py"
AGENTOS_DIR="/c/Users/mcwiz/Projects/AgentOS"

# Check if retry tool exists and use it for automatic retry on capacity errors
if [ -f "$RETRY_TOOL" ]; then
  echo "[GEMINI] Using AgentOS retry tool with exponential backoff..." >&2

  # Use retry tool - it handles MODEL_CAPACITY_EXHAUSTED automatically
  result=$(poetry run --directory "$AGENTOS_DIR" python "$RETRY_TOOL" \
    --prompt "$PROMPT" \
    --model "$REQUIRED_MODEL" 2>&1) || {
    exit_code=$?
    echo "$result" >&2

    # Check if it's a daily quota error (non-retryable)
    if echo "$result" | grep -qiE "daily.*quota|QUOTA_EXHAUSTED"; then
      echo "ERROR: Daily quota exhausted (non-retryable)" >&2
      exit 2
    fi

    echo "ERROR: Gemini retry tool failed (exit code: $exit_code)" >&2
    exit 1
  }
else
  # Fallback: Direct gemini call (no retry)
  echo "[GEMINI] Warning: Retry tool not found, using direct call (no retry)..." >&2

  result=$(gemini -p "$PROMPT" \
    --model "$REQUIRED_MODEL" \
    --output-format json 2>&1) || {
    echo "ERROR: Gemini CLI failed to execute" >&2
    echo "$result" >&2
    exit 1
  }

  # Check for 429 quota errors in raw output (only needed without retry tool)
  if echo "$result" | grep -qE "429|Resource exhausted|quota"; then
    echo "ERROR: Quota exhausted (429 error)" >&2
    echo "TIP: Install AgentOS retry tool for automatic retry" >&2
    exit 2
  fi
fi

# Handle response based on whether we used retry tool or direct call
# Retry tool returns plain text; direct call returns JSON

# Try to extract JSON portion (skip any non-JSON prefix like "Loaded cached credentials.")
json_output=$(echo "$result" | sed -n '/{/,$p')

# Check if we got valid JSON
if echo "$json_output" | jq -e '.stats.models' >/dev/null 2>&1; then
  # JSON mode: Parse models used from JSON stats
  models_json=$(echo "$json_output" | jq -r '.stats.models // {}')

  # Check for model downgrades
  downgrade=false
  models_used=()

  while IFS= read -r model; do
    # Trim any trailing whitespace/CR/LF
    model=$(echo "$model" | tr -d '\r\n')

    models_used+=("$model")

    # Check if this model is NOT one of the allowed models
    # Allow: gemini-3-pro-preview, gemini-3-pro (stable), or the explicitly required model
    if [[ "$model" != "$REQUIRED_MODEL" && "$model" != "gemini-3-pro" && "$model" != "gemini-3-pro-preview" ]]; then
      echo "ERROR: Model downgrade detected!" >&2
      echo "Required: $REQUIRED_MODEL" >&2
      echo "Actually used: $model" >&2
      downgrade=true
    fi
  done < <(echo "$models_json" | jq -r 'keys[]')

  if [ "$downgrade" = true ]; then
    echo "All models used: ${models_used[*]}" >&2
    exit 3
  fi

  # Success - output positive model verification to stderr (for capture/logging)
  echo "---GEMINI-MODEL-VERIFIED---" >&2
  echo "Model: ${models_used[*]}" >&2
  echo "Stats.models:" >&2
  echo "$models_json" | jq -c '.' >&2
  echo "---END-VERIFICATION---" >&2

  # Extract and output response only (no JSON wrapper) to stdout
  response=$(echo "$json_output" | jq -r '.response')
  echo "$response"
else
  # Plain text mode (from retry tool or agentic mode)
  # Model validation was done by retry tool; trust the result
  echo "---GEMINI-MODEL-VERIFIED---" >&2
  echo "Model: $REQUIRED_MODEL (via retry tool, model validation delegated)" >&2
  echo "---END-VERIFICATION---" >&2

  # Output plain text response
  echo "$result"
fi

exit 0
